@startuml

hide footbox
skinparam sequenceMessageAlign center
skinparam sequenceArrowFontSize 11
skinparam noteFontSize 11
skinparam monochrome true
skinparam lifelinestrategy solid
 
"End User" -> "Device Application" : deleteDeviceApplication
"Device Application" -> LAA : delete(sessionId, samSMFQDN, name)

LAA -> "End User" : requestUserConsentOrAuthentification
rnote over "End User": allow
LAA <-- "End User"
 
"LAA" -> "SAM SD" : DELETE_SAM_SERVICE(aspSDAid) 
"SAM SD" --> LAA : deleteStatusWord

 
LAA --> "Device Application" : notification(sessionId, aspSDAid, DELETE)
 
LAA --> "SAM SM" : notification(SAMSM_FQDN, sessionId, aspSDAid, DELETE)
@enduml
