@startuml

hide footbox
skinparam sequenceMessageAlign center
skinparam sequenceArrowFontSize 11
skinparam noteFontSize 11
skinparam monochrome true
skinparam lifelinestrategy solid
 
"End User" -> "Device Application" : deleteDeviceApplication
"Device Application" -> LAA : delete(sessionId, samSMFQDN, deleteScriptUri)

LAA -> "End User" : requestUserConsentOrAuthentification
rnote over "End User": allow
LAA <-- "End User"

rnote over "LAA", "SAM SM"
     Process executeScript(deleteScriptUri)
end rnote


 
LAA --> "Device Application" : notification(sessionId, aspSDAid, DELETE)
 
LAA --> "SAM SM" : notification(SAMSM_FQDN, sessionId, aspSDAid, DELETE)
@enduml