@startuml
 
hide footbox
skinparam sequenceMessageAlign center
skinparam sequenceArrowFontSize 11
skinparam noteFontSize 11
skinparam monochrome true
skinparam lifelinestrategy solid


rnote over "End User", "Device Application"
     "End User install a new Device Application
      containing a SAM script"
end rnote

"Device Application" -> LAA : install(sessionId, samSMFQDN, localScriptUri)
LAA -> "SAM SD" : GET_DATA(SAMEligibilityInfoTag)
"SAM SD" --> LAA : SAMEligibilityInfo  
LAA -> "SAM SD" : GET_DATA(CRDTag)
"SAM SD" --> LAA : CRD
LAA -> "SAM SD" : GET_DATA(CCITag)
"SAM SD" --> LAA : CCI
LAA -> "SAM SD" : GET_DATA(SAMCertifTag)
"SAM SD" --> LAA : SAMCertifs
"LAA" -> "LAA" : initiateInstallation(sessionId, SAMEligibilityInfos, DeviceInfo) 
 
rnote over "LAA", "End User"
     [0] End User interactions for user intent
end rnote

rnote over "LAA", "SAM SD"
     [1b] Process executeGPSERAMScriptFile(sessionId, localScriptUri)
end rnote
 
LAA --> "Device Application" : notification(sessionId, aspSDAid, INSTALL)
 
LAA --> "SAM SM" : notification(sessionId, aspSDAid, INSTALL)
@enduml
