@startuml
 
hide footbox
skinparam sequenceMessageAlign center
skinparam sequenceArrowFontSize 11
skinparam noteFontSize 11
skinparam monochrome true
skinparam lifelinestrategy solid
 
rnote over "End User", "Device application"
     "End User installs a new Device Application
      looking for a SAM script on SAM SM"
end rnote

"Device application" -> LAA : install(sessionId, samSMFQDN, localScriptUri=null)

rnote over "LAA", "SAM SD"
     [0] Process getSAMEligibilityInfos
end rnote

"LAA" -> "SAM SM" : initiateInstallation(sessionId, supportedSamCaIdentifiers, SAMEligibilityInfos, DeviceInfo)
"SAM SM" -> "SAM SM" : retrieveOrGenerateScript(sessionId)
"SAM SM" --> LAA : samEligibilityResponse(gpseramUri)
 
rnote over "LAA", "End User"
     [1] End User interactions for user intent
end rnote
 
rnote over "LAA", "SAM SM"
     [2a] Process executeGPSERAMScript(sessionId, gpseramUri)
end rnote
 
LAA --> "Device application" : notification(sessionId, samServiceIdentifier, INSTALL)
 
LAA --> "SAM SM" : notification(sessionId, samServiceIdentifier, INSTALL)
@enduml