
openapi: "3.0.3"
info:
  title: "LAA - SAM SM"
  version: "1.0.0"
  description: "This interface allows a Local Applet Assistant to manage exchanges with a SAM SM"
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
- name: "samSmService"
  description: "This service allows to process requests and notifications from LAA"
servers:
  - url: '{protocol}://{samfqdn}/gp/sam'
    variables:
      samfqdn:
        default: localhost
        description: sam server domain (or sam server domain + plus suffix) 
      protocol:
        description: http shall be used only for testing purpose
        enum:
          - http
          - https
        default: https
paths:
  /install:
    post:
      tags:
      - "samSmService"
      summary: "This function initiates the SAM-SM installation procedure"
      description: "This method is used by the LAA client to request to open session on SAM SM. LAA retrieves material from the SAM SD to be provided to the SAM-SM. On reception of this function call, the SAM-SM SHALL: 
      
      
          •  Check if the installation on the current SAM SD is possible (contactless support, memory left..)
          
          
          •  Create a SAM management session with the given identifier.
          
          
          •  Generate a script for the SAM service installation (including the ASP SD). This script can be generated dynamically (for instance in SCP11a) or can be only retrieved (for instance SCP11c) for this given SAM SD target. The sessionId for GP SE RAM session SHALL be reused.
          

        The SAM-SM MAY perform additional operations, which are out of scope of this specification."
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/sessionId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/samInstallMsg"
            examples:
                install:
                  summary: install message
                  externalValue: 'https://gaelrgerard.github.io/laa/spec/examples/install_req.json'
      responses:
        "200":
          description: "RAM session is successfully created or retrieved. functionExecutionStatus SHALL be set to RAM_SESSION_CREATED for normal execution"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/samManagementRespMsg"
              examples:
                install_ok:
                  summary: install resp with ram session
                  externalValue: 'https://gaelrgerard.github.io/laa/spec/examples/install_resp_ok.json'
                install_nok:
                  summary: install resp with failure
                  externalValue: 'https://gaelrgerard.github.io/laa/spec/examples/install_resp_nok.json'
        "409":
          description: "Conflict with already existing session"
        "500":
          description: "Unexpected error on server side"
  /delete:
    post:
      tags:
      - "samSmService"
      summary: "This function initiates the SAM-SM delete procedure"
      description: "This method is used by the LAA client to request the deletion of specific SAM Service identified by its asp AID"
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/sessionId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/samDeleteMsg"
      responses:
        "200":
          description: "RAM session is successfully created or retrieved. functionExecutionStatus SHALL be set to RAM_SESSION_CREATED"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/samManagementRespMsg"
              examples:
                delete_ok:
                  summary: delete resp with ram session
                  externalValue: "examples/delete_resp_ok.json"
                delete_nok:
                  summary: delete resp with failure
                  externalValue: "examples/delete_resp_nok.json"
        "409":
          description: "Conflict with already existing session"
        "500":
          description: "Unexpected error on server side"
  /notification:
    post:
      tags:
      - "samSmService"
      summary: "This function notifies the SAM SM of a SAM SD event"
      description: "This function is called by the LAA to notify the SAM-SM that a SAM Application Management Operation has  been performed on the SAM SD."
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/sessionId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/notificationMsg"
            examples:              
                notif_install_ok:
                  summary: install notification OK
                  externalValue: "notification_install_ok.json"
                notif_offline_install_ok:
                  summary: install notification OK for an offline script
                  externalValue: "notification_offline_install_script_ok.json"
                notif_delete_ok:
                  summary: delete notification OK
                  externalValue: "notification_delete_ok.json"
      responses:
        "200":
          description: "notification process successfully"
        "404":
          description: "Session id not found"
        "500":
          description: "Unexpected error on server side"
components:
  schemas:
    binData:
      description: "base 64 encoded bin data"
      type: "string"
      format: "byte"
      example: "dGhpcyBpcyBhbiBleGFtcGxl"

    secureElement:
      type: "object"
      properties:
        seType:
          type: "string"
          enum:
            - "ESE"
            - "UICC"
            - "EUICC_REMOVABLE"
            - "EUICC"
            - "EUICC_INTEGRATED"
            - "NOT_DEFINED"
            - "UNKNOWN"
        seId:
          type: "string"
          example: "89001012012341234012345678901224"
    aid:
      type: "string"
      pattern: "^([0-9A-F]{2}){5,16}$"
      example: "A00001510000"

    sessionId:
      type: "string"
      format: "uuid"
      example: "0f96af97-f879-45a2-a011-ee7439df3804"

    version:
      type: "string"
      example: "1.0.0"
      
    oid:
      type: "string"
      pattern: ^([0-2])((\.0)|(\.[1-9][0-9]*))*$
      example: "1.0"            
      
    installationStep:
      type: "string"
      enum:
            - "INSTALL"
            - "PERSO"
            - "DELETE"
            - "LOCK"
            - "UNLOCK"
    deviceInfo:
      type: "object"
      properties:
        openMobileApiVersion:
          $ref: "#/components/schemas/version"
    
    samCertificate:
      type: "object"
      required:
        - "data"
        - "certificateFormat"
      properties :
        data: 
          $ref: "#/components/schemas/binData"
        certificateFormat: 
          type: "string"
          enum:
            - "x509"
            - "GP"
    
    samEligibilityData:
      description: "this command alow to perform an eligibility check. samSDEligibilityData is the concatenation of the GET DATA responses performed on the SAM SD : CCI, CRD, SAMInfo"
      type: "object"
      required:
        - "secureElement"
        - "samVersion"
        - "samSDEligibilityData"
        - "deviceInfo"
        - "samCertificates"
      properties:
        secureElement:
          $ref: "#/components/schemas/secureElement"
        samVersion:
          $ref: "#/components/schemas/version"
        samSDEligibilityData:
          $ref: "#/components/schemas/binData"
        deviceInfo:
          $ref: "#/components/schemas/deviceInfo"
        samCertificates:
          type: "array"
          description: "sam certificate shall be ordered from the SAM SD certificate (first in the list) to the SAM CA (last in the list)"
          items:
            $ref: "#/components/schemas/samCertificate"  
  
    samServiceIdentifier:
     description: "used to uniquely identified a SAM service on a SAM SM"
     required:
        - "aspSdAid"
     properties:
        aspSdAid:
          $ref: "#/components/schemas/aid"
        samServiceName:
          type: string
          example: "awesome sam service"
        extraData:
          type: string
          example: "instance 1"
    
    samServiceScriptResp:
     description: "sam service script resp shall be used in case of local script execution. It is needed for the SAM SM in order to retrieve the ASP SD keys"
     required:
        - "scriptIdentifier"
        - "rapdus"
     properties:
        scriptIdentifier :
          type: string
          example: "delete sam service instance 1"
        apdus: 
          type: "array"
          description: "list of apdus"
          items:
            $ref: "#/components/schemas/apdu"
        rapdus: 
          type: "array"
          description: "list of corresponding rapdus"
          items:
            $ref: "#/components/schemas/apdu"        
    
                
    apdu:
      description: hexadecimal encoded APDU
      type: string
      pattern: '([0-9A-F]{2})*'
      
    functionExecutionStatus:
      description: "Whether the function has been processed correctly or not (like SGP22)"
      required:
        - "status"
      properties:
         status: 
          type: "string"
          enum:
                - "EXECUTED_SUCCESS"
                - "EXECUTED_WARNING"
                - "FAILED"
                - "EXPIRED"
                - "RAM_SESSION_CREATED" 
         statusCodeData:
          $ref: "#/components/schemas/statusCodeData"
    statusCodeData:
      description : 
       "status code data like GSMA RSP"
      required:
        - "subjectCode"
        - "reasonCode"
      properties:
        subjectCode:
          $ref: "#/components/schemas/oid"
        reasonCode:
          $ref: "#/components/schemas/oid"
        subjectIdentifier:
          type: string
          description: Identifier of the subject
        message:
          type: string
          description: Textual and human readable explanation
          example: "SAM SD capabilities is not compliant with SAM Service"
    
    samInstallMsg:
      description: "this msg alow to trigger an install on a SAM SD"
      type: "object"
      required:
        - "samEligibilityData"
        - "samServiceIdentifier"
      properties:
        samServiceIdentifier:
          $ref: "#/components/schemas/samServiceIdentifier"
        samEligibilityData:
          $ref: "#/components/schemas/samEligibilityData"
    
    samDeleteMsg:
      description: "this msg alow to trigger a delete on a SAM SD"
      type: "object"
      required:
        - "samServiceIdentifier"
      properties:
        samServiceIdentifier:
          $ref: "#/components/schemas/samServiceIdentifier"
     
    notificationMsg:
      description: "This is the data model for the notification msg"
      type: "object"
      required:
        - "functionExecutionStatus"
        - "installationStep"
        - "samServiceIdentifier"
      properties:
        functionExecutionStatus:
          $ref: "#/components/schemas/functionExecutionStatus"
        installationStep:
          $ref: "#/components/schemas/installationStep"
        samServiceIdentifier:
          $ref: "#/components/schemas/samServiceIdentifier"
        samServiceScriptResp: 
          $ref: "#/components/schemas/samServiceScriptResp"   
        extraData:
          type: "string"
          description: "can be set to indicate some useful extra data. For instance the installation mode"
    
    samManagementRespMsg:
      description: "This is the data model for the sam install or delete Response."
      type: "object"
      required:
        - "functionExecutionStatus"
      properties:
        functionExecutionStatus:
          $ref: "#/components/schemas/functionExecutionStatus"
        gpseramuri:
          type: string
          format: uri
          example: "https://sam-sm.server1.com/gp/seram/script1"
