
openapi: "3.0.3"
info:
  title: "LAA - SAM SM"
  version: "1.0.0"
  description: "This interface allows a Local Applet Assistant to manage exchanges with a SAM SM"
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
- name: "samApplicationManagementService"
  description: "This service allows to receive request from LAA"
servers:
  - url: '{protocol}://{samfqdn}/gp/sam'
    variables:
      samfqdn:
        default: localhost
        description: sam server domain (or sam server domain + plus suffix) 
      protocol:
        enum:
          - http
          - https
        default: https
paths:
  /install:
    post:
      tags:
      - "samApplicationManagementService"
      summary: "This function initiates the SAM-SM installation procedure"
      description: "This method is used by the LAA client to request to open session on SAM SM. LAA retrieves material from the SAM SD to be provided to the SAM-SM. On reception of this function call, the SAM-SM SHALL: 
      
      
          •  Check if the installation on the current SAM SD is possible (contactless support, memory left..)
          
          
          •  Create a SAM management session with the given identifier
          
          
          •  Generate a script for the SAM service installation (including the ASP SD). This script can be generated dynamically (for instance in SCP11a) or can be only retrieved (for instance SCP11c) for this given SAM SD target. The session id for GP SE RAM session SHALL be reused.
          

        The SAM-SM MAY perform additional operations, which are out of scope of this specification."
      parameters:
        - name: sessionID
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/sessionId"
      requestBody:
        content:
          application/json:
            schema:
              required:
              - "samInstallMsg"
              properties:
                samInstallMsg:
                  $ref: "#/components/schemas/samInstallMsg"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                required:
                - "samInstallResponse"
                properties:
                  samInstallResponse:
                    $ref: "#/components/schemas/samManagementRespMsg"
        "409":
          description: "Conflict with already existing session"
  /delete:
    post:
      tags:
      - "samApplicationManagementService"
      summary: "This function initiates the SAM-SM delete procedure"
      description: "This method is used by the LAA client to request the deletion of specific SAM Service identified by its asp AID"
      parameters:
        - name: sessionID
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/sessionId"
      requestBody:
        content:
          application/json:
            schema:
              required:
              - "samDeleteMsg"
              properties:
                samDeleteMsg:
                  $ref: "#/components/schemas/samDeleteMsg"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                required:
                - "samDeleteResponse"
                properties:
                  samDeleteResponse:
                    $ref: "#/components/schemas/samManagementRespMsg"
        "409":
          description: "Conflict with already existing session"
  /notification:
    post:
      tags:
      - "samApplicationManagementService"
      summary: "method used to notify the SAM SM of a SAM SD event"
      description: "This function is called by the LAA to notify the SAM-SM that a SAM Application Management Operation has successfully been performed on the SAM SD."
      parameters:
        - name: sessionID
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/sessionId"
      requestBody:
        content:
          application/json:
            schema:
              required:
              - "notificationMsg"
              properties:
                notificationMsg:
                  $ref: "#/components/schemas/notificationMsg"
      responses:
        "200":
          description: "OK"
        "404":
          description: Session id not found
components:
  schemas:
    binData:
      description: "base 64 encoded asn1 data"
      type: "string"
      format: "byte"

    secureElement:
      type: "object"
      properties:
        seType:
          type: "string"
          enum:
            - "eSE"
            - "uicc"
            - "euicc/removable"
            - "euicc/embedded"
            - "euicc/integrated"
            - "notdefined"
        seId:
          type: "string"
          example: "89001012012341234012345678901224"
    aid:
      type: "string"
      pattern: "^([0-9A-F]{2}){5,16}$"
      example: "A00001510000"

    sessionId:
      type: "string"
      format: "uuid"
      example: "0f96af97-f879-45a2-a011-ee7439df3804"

    version:
      type: "string"
      example: "1.0.0"
      
    installationStep:
      type: "string"
      enum:
            - "INSTALL"
            - "PERSO"
            - "DELETE"
    deviceInfo:
      type: "object"
      properties:
        openMobileApiVersion:
          $ref: "#/components/schemas/version"
    
    samCertificate:
      type: "object"
      required:
        - "data"
        - "certificateFormat"
      properties :
        data: 
          $ref: "#/components/schemas/binData"
        certificateFormat: 
          type: "string"
          enum:
            - "x509"
            - "GP"
    
    samEligibilityData:
      description: "this command alow to perform an eligibility check"
      type: "object"
      required:
        - "secureElement"
        - "samVersion"
        - "samSDEligibilityData"
        - "deviceInfo"
        - "samCertificates"
      properties:
        secureElement:
          $ref: "#/components/schemas/secureElement"
        samVersion:
          $ref: "#/components/schemas/version"
        samSDEligibilityData:
          $ref: "#/components/schemas/binData"
        deviceInfo:
          $ref: "#/components/schemas/deviceInfo"
        samCertificates:
          type: "array"
          description: "sam certificate shall be ordered from the SAM SD certiicate (first in the list) to the SAM CA (last in the list)"
          items:
            $ref: "#/components/schemas/samCertificate"  
  
    samServiceIdentifier:
     required:
        - "aspSdAid"
     properties:
        aspSdAid:
          $ref: "#/components/schemas/aid"
        extraData:
          type: string
                
    functionExecutionStatus:
      required:
        - "status"
      properties:
         status: 
          type: "string"
          enum:
                - "EXECUTED_SUCCESS"
                - "EXECUTED_WARNING"
                - "FAILED"
                - "EXPIRED"
                - "RAM_SESSION_CREATED" 
         statusCodeData:
          $ref: "#/components/schemas/statusCodeData"
    statusCodeData:
      description : 
       "status code data like GSMA RSP"
      required:
        - "subjectCode"
        - "reasonCode"
      properties:
        subjectCode:
          type: string
          description: OID of the subject code
        reasonCode:
          type: string
          description: OID of the reason code
        subjectIdentifier:
          type: string
          description: Identifier of the subject
        message:
          type: string
          description: Textual and human readable explanation
    
    samInstallMsg:
      description: "this msg alow to trigger an install on a SAM SD"
      type: "object"
      required:
        - "samEligibilityData"
        - "samServiceIdentifier"
      properties:
        samServiceIdentifier:
          $ref: "#/components/schemas/samServiceIdentifier"
        samEligibilityData:
          $ref: "#/components/schemas/samEligibilityData"
    
    samDeleteMsg:
      description: "this msg alow to trigger an delete on a SAM SD"
      type: "object"
      required:
        - "samServiceIdentifier"
      properties:
        samServiceIdentifier:
          $ref: "#/components/schemas/samServiceIdentifier"
     
    notificationMsg:
      description: "This is the data model for the notification msg"
      type: "object"
      required:
        - "functionExecutionStatus"
        - "installationStep"
        - "samServiceIdentifier"
      properties:
        functionExecutionStatus:
          $ref: "#/components/schemas/functionExecutionStatus"
        installationStep:
          $ref: "#/components/schemas/installationStep"
        samServiceIdentifier:
          $ref: "#/components/schemas/samServiceIdentifier"
    
    samManagementRespMsg:
      description: "This is the data model for the sam install or delete Response."
      type: "object"
      required:
        - "functionExecutionStatus"
      properties:
        functionExecutionStatus:
          $ref: "#/components/schemas/functionExecutionStatus"
        gpseramuri:
          type: string
          format: uri
          example: "https://sam-sm.server1.com/gp/seram/script1"
